---
#Azure Vars
resourceGroup: student2-rg
dnsLabel: student2
locaction: eastus
tagValues: {"application":"APP","cost":"COST","environment":"ENV","group":"GROUP","owner":"OWNER"}

#BIG-IP Vars
adminUsername: f5admin
adminPassword: ChangeMeNow123

#Instance Details
imageName: Best
instanceType: Standard_DS4_v2
numberOfExternalIps: 2
ntpServer: 0.pool.ntp.org
timeZone: UTC


#PAYG Vars
#licensedBandwidth: 25m

