---
#VARs for F5 BIG-IP

#F5 Intance
adminUsername: "{{ lookup('env', 'AZURE_STUDENT') }}"
adminPassword: "{{ lookup('env', 'AZURE_PW') }}"


#Create F5 BIG-IP VS
destination1: "10.0.2.14" 
destination2: "10.0.2.15"
vsName1: hackazon-vs-1
vsName2: hackazon-vs-2

vsPort: 3000
snat: Automap
poolName: hackazon-pool
allProfiles: http
