---
#VARs for F4 Azure ARM Template

#Azure
resourceGroup: f5-rg-studentX
dnsLabel: f5studentX
location: eastus

#F5 Intance
adminUsername: f5admin
adminPassword: 
#instanceName:
instanceType: Standard_DS4_v2
imageName:  Best
#bigIpVersion: 13.0.0300 | 12.1.2200 | latest

#BYOL
#licenseKey1:  
#licenseKey2: 


#PAYG
licensedBandwidth: 25m 

#BIG-IQ        
#bigIqLicewnseHost: 
#bigIqLicenseUsername:
#bigIqLicensePassword:
#bigIqLicwensePool:

#Network        
numberOfExternaslIps: 2
#vnetAddressPrefix:

#Cluster        
#enableNetworkFailover:
#internalLoadBalancerType:
#internalLoadBalanceProbePort:

#System                
#ntpServer:
#timeZone:
#restrictedSrvcAddress:
#tagValues:
#allowUasgeAnalytics:
