---
#- debug: msg="{{ inventory_hostname }}i {{ ansible_host }}"
  
  
- name: Create F5 BIG-IP VS
  bigip_virtual_server:
    destination: "{{ destination }}"      
    name: "{{ vsName }}"
    port: "{{ vsPort }}"
    snat: "{{ snat }}"
    pool: "{{ poolName }}"
    all_profiles: "{{ allProfiles }}"
    user: "{{ adminUsername }}"
    password: "{{ adminPassword }}"
    server: "{{ ansible_host }}"
    validate_certs: False
  delegate_to: localhost

