---
#- debug: msg="{{ inventory_hostname }}i {{ ansible_host }}"
  
  
- name: Create F5 BIG-IP VS1
  bigip_virtual_server:
    destination: "{{ destination1 }}"      
    name: "{{ vsName1 }}"
    port: "{{ vsPort }}"
    snat: "{{ snat }}"
    pool: "{{ poolName }}"
    all_profiles: "{{ allProfiles }}"
    user: "{{ adminUsername }}"
    password: "{{ adminPassword }}"
    server: "{{ ansible_host }}"
    validate_certs: False
  delegate_to: localhost

- name: Create F5 BIG-IP VS2
  bigip_virtual_server:
    destination: "{{ destination2 }}"      
    name: "{{ vsName2 }}"
    port: "{{ vsPort }}"
    snat: "{{ snat }}"
    pool: "{{ poolName }}"
    all_profiles: "{{ allProfiles }}"
    user: "{{ adminUsername }}"
    password: "{{ adminPassword }}"
    server: "{{ ansible_host }}"
    validate_certs: False
  delegate_to: localhost
