---
- azure_rm_securitygroup:
    resource_group: f5-rg-student1
    name: f5student1-int-nsg
    rules:
      - name: 'AllowSSH'
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 101
        direction: Inbound
