---
- azure_rm_securitygroup:
    resource_group: f5demo-rg
    name: f5demo-nsg
    rules:
      - name: 'AllowSSH'
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 101
        direction: Inbound
