---
- name: Add 80 to External Security Group
  azure_rm_securitygroup:
    resource_group: "{{ resourceGroup }}"
    name: "{{ externalNsg }}"
    rules:
      - name: 'AllowHTTP'
        protocol: Tcp
        destination_port_range: 80
        access: Allow
        priority: 101
        direction: Inbound

- name: Add 443 to External Security Group
  azure_rm_securitygroup:
    resource_group: "{{ resourceGroup }}"
    name: "{{ externalNsg }}"
    rules:
      - name: 'AllowHTTPS'
        protocol: Tcp
        destination_port_range: 443
        access: Allow
        priority: 102
        direction: Inbound


- name: Modify External load balancer
  azure_rm_loadbalancer:
    name: "{{ externalAlb }}"
    resource_group: "{{ resourceGroup }}"
    public_ip: "{{ externalPip0 }}"
    probe_protocol: Tcp
    probe_port: 80
    protocol: Tcp
    load_distribution: Default
    frontend_port: 80
    backend_port: 80
