---
#VARs for F5 BIG-IP

#F5 Intance
adminUsername: "{{ lookup('env', 'AZURE_STUDENT') }}"
adminPassword: "{{ lookup('env', 'AZURE_PW') }}"


#Create F5 BIG-IP VS
destination1: "10.0.2.12" 
destination2: "10.0.2.13"
vsName1: juice-shop-vs-1
vsName2: juice-shop-vs-2

vsPort: 3000
snat: Automap
poolName: juice-shop-pool
allProfiles: http
